services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./src:/var/www
    networks:
      - bruiloft
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "5173:5173"
      - "9003:9003"

  nginx:
    image: nginx:latest
    ports:
      - "8001:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - bruiloft
    restart: unless-stopped

networks:
  bruiloft:
    driver: bridge